### ISSUE TITLE
Always SyntaxError in openbsd/macppc

### ISSUE THREAD

**Issue by nanaya** [judofyr/duktape.rb#30]
For a (questionably) fun project, I'm trying Rails on an openbsd/macppc platform and needed an execjs runtime and then found this to be the only available runtime. Fast forward, it keeps failing on my system and even just running the example gives me `error parsing token` error.

For what it's worth, duktape (not the gem) itself seems to be running okay, at least for the most trivial example with their cli.

A hint on fixing this would be appreciated. Thanks.

```
dev@nanoka:~$ gem pristine duktape
Restoring gems to pristine condition...
Building native extensions.  This could take a while...
Restored duktape-1.3.0.2
dev@nanoka:~$ uname -a
OpenBSD nanoka.myconan.net 5.7 GENERIC#443 macppc
dev@nanoka:~$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [powerpc-openbsd5.7]
dev@nanoka:~$ cat duktest.rb
#!/usr/bin/env ruby

require 'duktape'

ctx = Duktape::Context.new
p ctx.eval_string('1 + 1')
dev@nanoka:~$ ./duktest.rb
./duktest.rb:6:in `eval_string': error parsing token (line 1) (Duktape::SyntaxError)
        from ./duktest.rb:6:in `<main>'
```

```
dev@nanoka:~/build/duktape-1.3.0$ make -f Makefile.cmdline
gcc -o duk  -Os -pedantic -std=c99 -Wall -fstrict-aliasing -fomit-frame-pointer -I./src    -DDUK_OPT_SELF_TESTS src/duktape.c examples/cmdline/duk_cmdline.c -lm
duk_util.h:509: warning: 'duk_raw_read_u16_be' declared inline after being called
duk_util.h:509: warning: previous declaration of 'duk_raw_read_u16_be' was here
duk_util.h:510: warning: 'duk_raw_read_u32_be' declared inline after being called
duk_util.h:510: warning: previous declaration of 'duk_raw_read_u32_be' was here
duk_util.h:511: warning: 'duk_raw_read_double_be' declared inline after being called
duk_util.h:511: warning: previous declaration of 'duk_raw_read_double_be' was here
duk_util.h:512: warning: 'duk_raw_write_u16_be' declared inline after being called
duk_util.h:512: warning: previous declaration of 'duk_raw_write_u16_be' was here
duk_util.h:513: warning: 'duk_raw_write_u32_be' declared inline after being called
duk_util.h:513: warning: previous declaration of 'duk_raw_write_u32_be' was here
duk_util.h:514: warning: 'duk_raw_write_double_be' declared inline after being called
duk_util.h:514: warning: previous declaration of 'duk_raw_write_double_be' was here
/tmp//ccTRtPqI.o(.text+0x4150): In function `duk__format_parts_iso8601':
: warning: sprintf() is often misused, please use snprintf()
dev@nanoka:~/build/duktape-1.3.0$ ./duk
((o) Duktape [no readline] 1.3.0 (v1.3.0)
duk> print('hello world!')
hello world!
= undefined
duk> = undefined
Cleaning up...
```

**Comment by judofyr** [comment]
Interesting. I don't quite know what the issue could be.

Maybe it's related to the way we do encoding? Try this patch:

```diff
diff --git a/ext/duktape/duktape_ext.c b/ext/duktape/duktape_ext.c
index 1c20b54..e6892b7 100644
--- a/ext/duktape/duktape_ext.c
+++ b/ext/duktape/duktape_ext.c
@@ -198,7 +198,7 @@ static VALUE ctx_stack_to_value(struct state *state, int index)
     case DUK_TYPE_STRING:
       buf = duk_get_lstring(ctx, index, &len);
       VALUE str = rb_str_new(buf, len);
-      return decode_cesu8(state, str);
+      return str;
 
     case DUK_TYPE_OBJECT:
       if (duk_is_function(ctx, index)) {
@@ -256,7 +256,7 @@ static void ctx_push_ruby_object(struct state *state, VALUE obj)
       return;
 
     case T_STRING:
-      str = encode_cesu8(state, obj);
+      str = obj;
       duk_push_lstring(ctx, RSTRING_PTR(str), RSTRING_LEN(str));
       return;


```

(Yes, the trailing newlines are required)

Then compile and run tests like this:

```
$ git apply f.patch
$ bundle    # install dependencies
$ bundle exec rake   # run tests
```

**Comment by judofyr** [comment]
You could also see if changing this line fixes anything: https://github.com/judofyr/duktape.rb/blob/432da9960b651458bc65204d930e672cb5d4fcd6/ext/duktape/duktape_ext.c#L591

Change `UTF-16LE` to `UTF-16BE`. Again: Use `bundle exec rake` to run tests.

**Comment by nanaya** [comment]
Awesome, either patches worked for my simple script. I didn't have full repo cloned - I just updated the file in-place and recompile.

Currently running the test... (will take a while)

**Comment by judofyr** [comment]
I don't have any big-endian machine here, but I think this commit is sound: 05b8aaae8c37ff3159774a967de2fcd25475e5a4. The next release of Duktape will include this.

You can test it by adding the gem source directly in the Gemfile:

```ruby
gem 'duktape', github: 'judofyr/duktape.rb', ref: '05b8aaae8c37ff3159774a967de2fcd25475e5a4'
```

If you can verify that it works with this commit I can push out a new release.

**Comment by nanaya** [comment]
That commit passes tests on my system.

```
dev@nanoka:~/git/duktape.rb$ git st
HEAD detached at 05b8aaa
nothing to commit, working directory clean
dev@nanoka:~/git/duktape.rb$ be rake
mkdir -p tmp/powerpc-openbsd5.7/duktape_ext/2.2.3
cd tmp/powerpc-openbsd5.7/duktape_ext/2.2.3
/home/dev/apps/ruby22/bin/ruby -I. ../../../../ext/duktape/extconf.rb
creating Makefile
cd -
cd tmp/powerpc-openbsd5.7/duktape_ext/2.2.3
gmake
compiling ../../../../ext/duktape/duktape.c
duk_util.h:509: warning: 'duk_raw_read_u16_be' declared inline after being called
duk_util.h:509: warning: previous declaration of 'duk_raw_read_u16_be' was here
duk_util.h:510: warning: 'duk_raw_read_u32_be' declared inline after being called
duk_util.h:510: warning: previous declaration of 'duk_raw_read_u32_be' was here
duk_util.h:511: warning: 'duk_raw_read_double_be' declared inline after being called
duk_util.h:511: warning: previous declaration of 'duk_raw_read_double_be' was here
duk_util.h:512: warning: 'duk_raw_write_u16_be' declared inline after being called
duk_util.h:512: warning: previous declaration of 'duk_raw_write_u16_be' was here
duk_util.h:513: warning: 'duk_raw_write_u32_be' declared inline after being called
duk_util.h:513: warning: previous declaration of 'duk_raw_write_u32_be' was here
duk_util.h:514: warning: 'duk_raw_write_double_be' declared inline after being called
duk_util.h:514: warning: previous declaration of 'duk_raw_write_double_be' was here
compiling ../../../../ext/duktape/duktape_ext.c
../../../../ext/duktape/duktape_ext.c: In function 'ctx_alloc':
../../../../ext/duktape/duktape_ext.c:67: warning: ISO C90 forbids mixed declarations and code
../../../../ext/duktape/duktape_ext.c: In function 'encode_cesu8':
../../../../ext/duktape/duktape_ext.c:139: warning: ISO C90 forbids mixed declarations and code
../../../../ext/duktape/duktape_ext.c: In function 'decode_cesu8':
../../../../ext/duktape/duktape_ext.c:163: warning: ISO C90 forbids mixed declarations and code
../../../../ext/duktape/duktape_ext.c:169: warning: ISO C90 forbids mixed declarations and code
../../../../ext/duktape/duktape_ext.c: In function 'ctx_stack_to_value':
../../../../ext/duktape/duktape_ext.c:200: warning: ISO C90 forbids mixed declarations and code
../../../../ext/duktape/duktape_ext.c: In function 'raise_ctx_error':
../../../../ext/duktape/duktape_ext.c:312: warning: ISO C90 forbids mixed declarations and code
../../../../ext/duktape/duktape_ext.c:315: warning: ISO C90 forbids mixed declarations and code
../../../../ext/duktape/duktape_ext.c: In function 'ctx_eval_string':
../../../../ext/duktape/duktape_ext.c:337: warning: ISO C90 forbids mixed declarations and code
../../../../ext/duktape/duktape_ext.c:360: warning: ISO C90 forbids mixed declarations and code
../../../../ext/duktape/duktape_ext.c: In function 'ctx_exec_string':
../../../../ext/duktape/duktape_ext.c:381: warning: ISO C90 forbids mixed declarations and code
../../../../ext/duktape/duktape_ext.c: In function 'ctx_get_one_prop':
../../../../ext/duktape/duktape_ext.c:418: warning: ISO C90 forbids mixed declarations and code
../../../../ext/duktape/duktape_ext.c: In function 'ctx_get_nested_prop':
../../../../ext/duktape/duktape_ext.c:439: warning: ISO C90 forbids mixed declarations and code
../../../../ext/duktape/duktape_ext.c: In function 'ctx_get_prop':
../../../../ext/duktape/duktape_ext.c:476: warning: ISO C90 forbids mixed declarations and code
../../../../ext/duktape/duktape_ext.c: In function 'ctx_call_prop':
../../../../ext/duktape/duktape_ext.c:499: warning: ISO C90 forbids mixed declarations and code
../../../../ext/duktape/duktape_ext.c:517: warning: ISO C90 forbids mixed declarations and code
../../../../ext/duktape/duktape_ext.c: In function 'ctx_initialize':
../../../../ext/duktape/duktape_ext.c:562: warning: ISO C90 forbids mixed declarations and code
linking shared-object duktape_ext.so
cd -
mkdir -p tmp/powerpc-openbsd5.7/stage/lib
cp CHANGELOG.md tmp/powerpc-openbsd5.7/stage/CHANGELOG.md
cp README.md tmp/powerpc-openbsd5.7/stage/README.md
mkdir -p tmp/powerpc-openbsd5.7/stage/ext/duktape
cp ext/duktape/duk_config.h tmp/powerpc-openbsd5.7/stage/ext/duktape/duk_config.h
cp ext/duktape/duktape.c tmp/powerpc-openbsd5.7/stage/ext/duktape/duktape.c
cp ext/duktape/duktape.h tmp/powerpc-openbsd5.7/stage/ext/duktape/duktape.h
cp ext/duktape/duktape_ext.c tmp/powerpc-openbsd5.7/stage/ext/duktape/duktape_ext.c
cp ext/duktape/extconf.rb tmp/powerpc-openbsd5.7/stage/ext/duktape/extconf.rb
cp lib/duktape.rb tmp/powerpc-openbsd5.7/stage/lib/duktape.rb
mkdir -p tmp/powerpc-openbsd5.7/stage/lib/duktape
cp lib/duktape/version.rb tmp/powerpc-openbsd5.7/stage/lib/duktape/version.rb
install -c tmp/powerpc-openbsd5.7/duktape_ext/2.2.3/duktape_ext.so lib/duktape_ext.so
cp tmp/powerpc-openbsd5.7/duktape_ext/2.2.3/duktape_ext.so tmp/powerpc-openbsd5.7/stage/lib/duktape_ext.so
/home/dev/apps/ruby22/bin/ruby test/test_duktape.rb
Run options: --seed 4865

# Running:

...................................................................................

Finished in 9.591057s, 8.6539 runs/s, 1274.1035 assertions/s.

83 runs, 12220 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by judofyr** [comment]
That's awesome! I just released [v1.3.0.3](https://rubygems.org/gems/duktape/versions/1.3.0.3) with the patch.

**Comment by nanaya** [comment]
Thanks :+1:

**Comment by judofyr** [comment]
Cheers! Just open more issues if you have any problems. I'm guessing macppc isn't the easiest machine to work with.

Seems like the date is wrong on rubygems.org though. Next released gem will have the correct release date. Oh well, you can always check the [CHANGELOG.md](https://github.com/judofyr/duktape.rb/blob/master/CHANGELOG.md) for the actual dates.
